# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   name = "memcached"

   config.vm.define name do |host|
            host.vm.hostname = name
            host.vm.box = "hashicorp/precise64"
            host.vm.network :private_network, ip: "192.168.1.1"
            host.vm.provision "shell", path: "setup.sh"
        end
end
